### ISSUE TITLE
question: status of fork

### ISSUE THREAD

**Issue by braver** [simurai/tone-dark-syntax#1]
@simurai I was wondering what is currently holding this fork back? I loved the original idea using it a few months back and am interested in spending some time on it. Perhaps I can contribute something towards making this releasable?

**Comment by simurai** [comment]
I guess not much.. Well, it's not optimized for a lot of languages. But if the README has a note about which languages are already supported, I think it should be fine.

**Comment by simurai** [comment]
@braver Ok, it's now published and called DuoTone: https://github.com/simurai/duotone-dark-syntax

**Comment by braver** [comment]
awesome :tada:
