### ISSUE TITLE
No bracket matching in Python, MD, and LaTeX

### ISSUE THREAD

**Issue by avonmoll** [simurai/tone-dark-syntax#4]
Bracket matching seems to work okay for things like HTML tags (both with HTML grammar selected and markdown grammar selected), but other things that are caught by the Bracket Matcher package are not marked as such by this syntax theme. I'm not sure what the issue is since the `.bracket-matcher .region` is being selected in the `editor.less` file and is being assigned a value.

Adding the following to my `styles.less` seemed to make everything work:

```.less
.bracket-matcher {
  position: absolute;
  border: 1px solid rgba(0, 0, 0, 0);
  z-index: 1;
}
```

I'm not knowledgeable enough to say what the proper fix to this repo is.

**Comment by simurai** [comment]
Thanks for reporting. 🙇  I think the problem is that the cursor line covers the bracket-matcher highlights. In #5 the background uses transparency to make stuff underneath visible.

**Comment by avonmoll** [comment]
Awesome thanks!
