### ISSUE TITLE
UI colors

### ISSUE THREAD

**Issue by PascalPixel** [simurai/tone-dark-syntax#7]
Would it be possible to have the UI colors follow the background color set for the editor?

**Comment by simurai** [comment]
What's the UI theme you're using?

Once you changed the colors in the Tone Syntax theme settings, you have to click on "Sync UI". That should make some UI themes pick up the colors. Like One dark/light UI.

<img width="299" alt="screen shot 2018-02-01 at 2 54 44 pm" src="https://user-images.githubusercontent.com/378023/35705630-46083dd2-0760-11e8-8c82-a8e1fcf430c6.png">

**Comment by PascalPixel** [comment]
Reading is hard 😰
