### ISSUE TITLE
Search is unsupported/broken

### ISSUE THREAD

**Issue by iduuck** [simurai/tone-dark-syntax#9]
I really love the theme, but the search seems broken. Anyone willing to help me out with this?

![image](https://user-images.githubusercontent.com/325241/52338589-1b261c00-2a0b-11e9-8796-64b68025e0e2.png)

**Comment by simurai** [comment]
Is it fixed when reloading Atom? I have seen this issue when switching between light and dark themes without reloading.

**Comment by iduuck** [comment]
Works afterwards, thanks!! So this is an Atom bug?

**Comment by simurai** [comment]
> So this is an Atom bug?

Yeah, it has something to do with not all colors getting updated everywhere when switching themes.
